# Generated by Django 4.1.3 on 2022-12-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('dicr', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('png1', models.ImageField(upload_to='')),
                ('png2', models.ImageField(upload_to='')),
                ('png3', models.ImageField(upload_to='')),
            ],
        ),
    ]
